[2021-08-12 15:36:30,476] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: parallel_dag_03.task_5 2021-08-09T00:00:00+00:00 [queued]>
[2021-08-12 15:36:30,503] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: parallel_dag_03.task_5 2021-08-09T00:00:00+00:00 [queued]>
[2021-08-12 15:36:30,516] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2021-08-12 15:36:30,517] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2021-08-12 15:36:30,517] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2021-08-12 15:36:30,530] {taskinstance.py:1107} INFO - Executing <Task(BashOperator): task_5> on 2021-08-09T00:00:00+00:00
[2021-08-12 15:36:30,538] {standard_task_runner.py:52} INFO - Started process 12541 to run task
[2021-08-12 15:36:30,545] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'parallel_dag_03', 'task_5', '2021-08-09T00:00:00+00:00', '--job-id', '149', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/task_example.py', '--cfg-path', '/tmp/tmpgzs9eiap', '--error-file', '/tmp/tmp9zkyv3vg']
[2021-08-12 15:36:30,547] {standard_task_runner.py:77} INFO - Job 149: Subtask task_5
[2021-08-12 15:36:30,601] {logging_mixin.py:104} INFO - Running <TaskInstance: parallel_dag_03.task_5 2021-08-09T00:00:00+00:00 [running]> on host adam
[2021-08-12 15:36:30,670] {taskinstance.py:1300} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=parallel_dag_03
AIRFLOW_CTX_TASK_ID=task_5
AIRFLOW_CTX_EXECUTION_DATE=2021-08-09T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-08-09T00:00:00+00:00
[2021-08-12 15:36:30,671] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2021-08-12 15:36:30,672] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'echo hello from airflow > ~/Documents/hello_airflow.txt']
[2021-08-12 15:36:30,712] {subprocess.py:74} INFO - Output:
[2021-08-12 15:36:30,716] {subprocess.py:82} INFO - Command exited with return code 0
[2021-08-12 15:36:30,753] {taskinstance.py:1204} INFO - Marking task as SUCCESS. dag_id=parallel_dag_03, task_id=task_5, execution_date=20210809T000000, start_date=20210812T133630, end_date=20210812T133630
[2021-08-12 15:36:30,803] {taskinstance.py:1265} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-08-12 15:36:30,847] {local_task_job.py:149} INFO - Task exited with return code 0
