[2021-08-12 15:30:13,617] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: parallel_dag_03.processing_tasks.jupyter_task.task_1 2021-08-08T00:00:00+00:00 [queued]>
[2021-08-12 15:30:13,621] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: parallel_dag_03.processing_tasks.jupyter_task.task_1 2021-08-08T00:00:00+00:00 [queued]>
[2021-08-12 15:30:13,621] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2021-08-12 15:30:13,622] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2021-08-12 15:30:13,622] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2021-08-12 15:30:13,628] {taskinstance.py:1107} INFO - Executing <Task(BashOperator): processing_tasks.jupyter_task.task_1> on 2021-08-08T00:00:00+00:00
[2021-08-12 15:30:13,630] {standard_task_runner.py:52} INFO - Started process 504377 to run task
[2021-08-12 15:30:13,633] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'parallel_dag_03', 'processing_tasks.jupyter_task.task_1', '2021-08-08T00:00:00+00:00', '--job-id', '115', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/task_example.py', '--cfg-path', '/tmp/tmp9w5ruxib', '--error-file', '/tmp/tmpt9zi2n59']
[2021-08-12 15:30:13,634] {standard_task_runner.py:77} INFO - Job 115: Subtask processing_tasks.jupyter_task.task_1
[2021-08-12 15:30:13,652] {logging_mixin.py:104} INFO - Running <TaskInstance: parallel_dag_03.processing_tasks.jupyter_task.task_1 2021-08-08T00:00:00+00:00 [running]> on host adam
[2021-08-12 15:30:13,673] {taskinstance.py:1300} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=parallel_dag_03
AIRFLOW_CTX_TASK_ID=processing_tasks.jupyter_task.task_1
AIRFLOW_CTX_EXECUTION_DATE=2021-08-08T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-08-08T00:00:00+00:00
[2021-08-12 15:30:13,674] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2021-08-12 15:30:13,674] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'echo hello']
[2021-08-12 15:30:13,679] {subprocess.py:74} INFO - Output:
[2021-08-12 15:30:13,680] {subprocess.py:78} INFO - hello
[2021-08-12 15:30:13,680] {subprocess.py:82} INFO - Command exited with return code 0
[2021-08-12 15:30:13,691] {taskinstance.py:1204} INFO - Marking task as SUCCESS. dag_id=parallel_dag_03, task_id=processing_tasks.jupyter_task.task_1, execution_date=20210808T000000, start_date=20210812T133013, end_date=20210812T133013
[2021-08-12 15:30:13,718] {taskinstance.py:1265} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-08-12 15:30:13,764] {local_task_job.py:149} INFO - Task exited with return code 0
