[2021-08-12 15:26:59,424] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: parallel_dag_03.task_4 2021-08-12T13:26:48.150873+00:00 [queued]>
[2021-08-12 15:26:59,432] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: parallel_dag_03.task_4 2021-08-12T13:26:48.150873+00:00 [queued]>
[2021-08-12 15:26:59,433] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2021-08-12 15:26:59,433] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2021-08-12 15:26:59,433] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2021-08-12 15:26:59,450] {taskinstance.py:1107} INFO - Executing <Task(BashOperator): task_4> on 2021-08-12T13:26:48.150873+00:00
[2021-08-12 15:26:59,452] {standard_task_runner.py:52} INFO - Started process 500046 to run task
[2021-08-12 15:26:59,456] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'parallel_dag_03', 'task_4', '2021-08-12T13:26:48.150873+00:00', '--job-id', '134', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/task_example.py', '--cfg-path', '/tmp/tmpz7ummuxg', '--error-file', '/tmp/tmpyv3z09kx']
[2021-08-12 15:26:59,456] {standard_task_runner.py:77} INFO - Job 134: Subtask task_4
[2021-08-12 15:26:59,477] {logging_mixin.py:104} INFO - Running <TaskInstance: parallel_dag_03.task_4 2021-08-12T13:26:48.150873+00:00 [running]> on host adam
[2021-08-12 15:26:59,503] {taskinstance.py:1300} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=parallel_dag_03
AIRFLOW_CTX_TASK_ID=task_4
AIRFLOW_CTX_EXECUTION_DATE=2021-08-12T13:26:48.150873+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-08-12T13:26:48.150873+00:00
[2021-08-12 15:26:59,504] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2021-08-12 15:26:59,504] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'firefox gmail.com']
[2021-08-12 15:26:59,511] {subprocess.py:74} INFO - Output:
[2021-08-12 15:26:59,763] {subprocess.py:82} INFO - Command exited with return code 0
[2021-08-12 15:26:59,796] {taskinstance.py:1204} INFO - Marking task as SUCCESS. dag_id=parallel_dag_03, task_id=task_4, execution_date=20210812T132648, start_date=20210812T132659, end_date=20210812T132659
[2021-08-12 15:26:59,818] {taskinstance.py:1265} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-08-12 15:26:59,828] {local_task_job.py:149} INFO - Task exited with return code 0
