[2021-08-12 15:36:07,623] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: parallel_dag_03.task_5 2021-08-08T00:00:00+00:00 [queued]>
[2021-08-12 15:36:07,633] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: parallel_dag_03.task_5 2021-08-08T00:00:00+00:00 [queued]>
[2021-08-12 15:36:07,633] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2021-08-12 15:36:07,634] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2021-08-12 15:36:07,634] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2021-08-12 15:36:07,642] {taskinstance.py:1107} INFO - Executing <Task(BashOperator): task_5> on 2021-08-08T00:00:00+00:00
[2021-08-12 15:36:07,646] {standard_task_runner.py:52} INFO - Started process 11902 to run task
[2021-08-12 15:36:07,653] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'parallel_dag_03', 'task_5', '2021-08-08T00:00:00+00:00', '--job-id', '143', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/task_example.py', '--cfg-path', '/tmp/tmpjjxufgyz', '--error-file', '/tmp/tmpogy6m2s_']
[2021-08-12 15:36:07,654] {standard_task_runner.py:77} INFO - Job 143: Subtask task_5
[2021-08-12 15:36:07,683] {logging_mixin.py:104} INFO - Running <TaskInstance: parallel_dag_03.task_5 2021-08-08T00:00:00+00:00 [running]> on host adam
[2021-08-12 15:36:07,717] {taskinstance.py:1300} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=parallel_dag_03
AIRFLOW_CTX_TASK_ID=task_5
AIRFLOW_CTX_EXECUTION_DATE=2021-08-08T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-08-08T00:00:00+00:00
[2021-08-12 15:36:07,718] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2021-08-12 15:36:07,719] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'echo hello from airflow > ~/Documents/hello_airflow.txt']
[2021-08-12 15:36:07,725] {subprocess.py:74} INFO - Output:
[2021-08-12 15:36:07,728] {subprocess.py:82} INFO - Command exited with return code 0
[2021-08-12 15:36:07,750] {taskinstance.py:1204} INFO - Marking task as SUCCESS. dag_id=parallel_dag_03, task_id=task_5, execution_date=20210808T000000, start_date=20210812T133607, end_date=20210812T133607
[2021-08-12 15:36:07,772] {taskinstance.py:1265} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-08-12 15:36:07,784] {local_task_job.py:149} INFO - Task exited with return code 0
