[2021-08-12 10:34:46,899] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: parallel_dag.task_2 2021-01-05T00:00:00+00:00 [queued]>
[2021-08-12 10:34:46,903] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: parallel_dag.task_2 2021-01-05T00:00:00+00:00 [queued]>
[2021-08-12 10:34:46,903] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2021-08-12 10:34:46,903] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2021-08-12 10:34:46,903] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2021-08-12 10:34:46,910] {taskinstance.py:1107} INFO - Executing <Task(BashOperator): task_2> on 2021-01-05T00:00:00+00:00
[2021-08-12 10:34:46,912] {standard_task_runner.py:52} INFO - Started process 130231 to run task
[2021-08-12 10:34:46,915] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'parallel_dag', 'task_2', '2021-01-05T00:00:00+00:00', '--job-id', '42', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/subdag_example.py', '--cfg-path', '/tmp/tmpp_zb7kye', '--error-file', '/tmp/tmpd5mihph_']
[2021-08-12 10:34:46,916] {standard_task_runner.py:77} INFO - Job 42: Subtask task_2
[2021-08-12 10:34:46,935] {logging_mixin.py:104} INFO - Running <TaskInstance: parallel_dag.task_2 2021-01-05T00:00:00+00:00 [running]> on host adam
[2021-08-12 10:34:46,957] {taskinstance.py:1300} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=parallel_dag
AIRFLOW_CTX_TASK_ID=task_2
AIRFLOW_CTX_EXECUTION_DATE=2021-01-05T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-01-05T00:00:00+00:00
[2021-08-12 10:34:46,957] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2021-08-12 10:34:46,958] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'echo task 2']
[2021-08-12 10:34:46,962] {subprocess.py:74} INFO - Output:
[2021-08-12 10:34:46,963] {subprocess.py:78} INFO - task 2
[2021-08-12 10:34:46,963] {subprocess.py:82} INFO - Command exited with return code 0
[2021-08-12 10:34:46,974] {taskinstance.py:1204} INFO - Marking task as SUCCESS. dag_id=parallel_dag, task_id=task_2, execution_date=20210105T000000, start_date=20210812T083446, end_date=20210812T083446
[2021-08-12 10:34:46,988] {taskinstance.py:1265} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-08-12 10:34:47,006] {local_task_job.py:149} INFO - Task exited with return code 0
