[2021-08-12 15:25:20,779] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: parallel_dag_03.task_4 2021-08-12T13:24:09.630789+00:00 [queued]>
[2021-08-12 15:25:20,794] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: parallel_dag_03.task_4 2021-08-12T13:24:09.630789+00:00 [queued]>
[2021-08-12 15:25:20,795] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2021-08-12 15:25:20,795] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2021-08-12 15:25:20,795] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2021-08-12 15:25:20,806] {taskinstance.py:1107} INFO - Executing <Task(BashOperator): task_4> on 2021-08-12T13:24:09.630789+00:00
[2021-08-12 15:25:20,811] {standard_task_runner.py:52} INFO - Started process 497797 to run task
[2021-08-12 15:25:20,821] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'parallel_dag_03', 'task_4', '2021-08-12T13:24:09.630789+00:00', '--job-id', '122', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/task_example.py', '--cfg-path', '/tmp/tmpwr8fwi9h', '--error-file', '/tmp/tmp55_m4rwm']
[2021-08-12 15:25:20,822] {standard_task_runner.py:77} INFO - Job 122: Subtask task_4
[2021-08-12 15:25:20,866] {logging_mixin.py:104} INFO - Running <TaskInstance: parallel_dag_03.task_4 2021-08-12T13:24:09.630789+00:00 [running]> on host adam
[2021-08-12 15:25:20,928] {taskinstance.py:1300} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=parallel_dag_03
AIRFLOW_CTX_TASK_ID=task_4
AIRFLOW_CTX_EXECUTION_DATE=2021-08-12T13:24:09.630789+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-08-12T13:24:09.630789+00:00
[2021-08-12 15:25:20,931] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2021-08-12 15:25:20,931] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'firefox gmail.com']
[2021-08-12 15:25:20,963] {subprocess.py:74} INFO - Output:
[2021-08-12 15:25:21,187] {subprocess.py:82} INFO - Command exited with return code 0
[2021-08-12 15:25:21,219] {taskinstance.py:1204} INFO - Marking task as SUCCESS. dag_id=parallel_dag_03, task_id=task_4, execution_date=20210812T132409, start_date=20210812T132520, end_date=20210812T132521
[2021-08-12 15:25:21,242] {taskinstance.py:1265} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-08-12 15:25:21,273] {local_task_job.py:149} INFO - Task exited with return code 0
