[2021-08-12 10:34:35,390] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: parallel_dag.task_2 2021-01-02T00:00:00+00:00 [queued]>
[2021-08-12 10:34:35,394] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: parallel_dag.task_2 2021-01-02T00:00:00+00:00 [queued]>
[2021-08-12 10:34:35,395] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2021-08-12 10:34:35,395] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2021-08-12 10:34:35,395] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2021-08-12 10:34:35,403] {taskinstance.py:1107} INFO - Executing <Task(BashOperator): task_2> on 2021-01-02T00:00:00+00:00
[2021-08-12 10:34:35,405] {standard_task_runner.py:52} INFO - Started process 129986 to run task
[2021-08-12 10:34:35,408] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'parallel_dag', 'task_2', '2021-01-02T00:00:00+00:00', '--job-id', '33', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/subdag_example.py', '--cfg-path', '/tmp/tmpnbv12iwx', '--error-file', '/tmp/tmpt6l0errz']
[2021-08-12 10:34:35,409] {standard_task_runner.py:77} INFO - Job 33: Subtask task_2
[2021-08-12 10:34:35,434] {logging_mixin.py:104} INFO - Running <TaskInstance: parallel_dag.task_2 2021-01-02T00:00:00+00:00 [running]> on host adam
[2021-08-12 10:34:35,468] {taskinstance.py:1300} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=parallel_dag
AIRFLOW_CTX_TASK_ID=task_2
AIRFLOW_CTX_EXECUTION_DATE=2021-01-02T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-01-02T00:00:00+00:00
[2021-08-12 10:34:35,468] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2021-08-12 10:34:35,469] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'echo task 2']
[2021-08-12 10:34:35,473] {subprocess.py:74} INFO - Output:
[2021-08-12 10:34:35,474] {subprocess.py:78} INFO - task 2
[2021-08-12 10:34:35,475] {subprocess.py:82} INFO - Command exited with return code 0
[2021-08-12 10:34:35,488] {taskinstance.py:1204} INFO - Marking task as SUCCESS. dag_id=parallel_dag, task_id=task_2, execution_date=20210102T000000, start_date=20210812T083435, end_date=20210812T083435
[2021-08-12 10:34:35,504] {taskinstance.py:1265} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-08-12 10:34:35,539] {local_task_job.py:149} INFO - Task exited with return code 0
