[2021-08-12 15:30:44,227] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: parallel_dag_03.task_4 2021-08-12T13:29:08.614696+00:00 [queued]>
[2021-08-12 15:30:44,238] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: parallel_dag_03.task_4 2021-08-12T13:29:08.614696+00:00 [queued]>
[2021-08-12 15:30:44,238] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2021-08-12 15:30:44,238] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2021-08-12 15:30:44,238] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2021-08-12 15:30:44,248] {taskinstance.py:1107} INFO - Executing <Task(BashOperator): task_4> on 2021-08-12T13:29:08.614696+00:00
[2021-08-12 15:30:44,252] {standard_task_runner.py:52} INFO - Started process 505068 to run task
[2021-08-12 15:30:44,257] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'parallel_dag_03', 'task_4', '2021-08-12T13:29:08.614696+00:00', '--job-id', '132', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/task_example.py', '--cfg-path', '/tmp/tmpumrtx6c0', '--error-file', '/tmp/tmp00bt5y65']
[2021-08-12 15:30:44,258] {standard_task_runner.py:77} INFO - Job 132: Subtask task_4
[2021-08-12 15:30:44,282] {logging_mixin.py:104} INFO - Running <TaskInstance: parallel_dag_03.task_4 2021-08-12T13:29:08.614696+00:00 [running]> on host adam
[2021-08-12 15:30:44,316] {taskinstance.py:1300} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=parallel_dag_03
AIRFLOW_CTX_TASK_ID=task_4
AIRFLOW_CTX_EXECUTION_DATE=2021-08-12T13:29:08.614696+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-08-12T13:29:08.614696+00:00
[2021-08-12 15:30:44,318] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2021-08-12 15:30:44,319] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'firefox gmail.com']
[2021-08-12 15:30:44,326] {subprocess.py:74} INFO - Output:
[2021-08-12 15:30:44,519] {subprocess.py:82} INFO - Command exited with return code 0
[2021-08-12 15:30:44,539] {taskinstance.py:1204} INFO - Marking task as SUCCESS. dag_id=parallel_dag_03, task_id=task_4, execution_date=20210812T132908, start_date=20210812T133044, end_date=20210812T133044
[2021-08-12 15:30:44,565] {taskinstance.py:1265} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-08-12 15:30:44,588] {local_task_job.py:149} INFO - Task exited with return code 0
